name: smart_documents_scanner
description: "Application for scanning and recognizing documents"
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.8
  camera: 0.12.0+2
  path_provider: 2.1.6
  google_mlkit_text_recognition: 0.16.0
  flutter_bloc: 9.1.1
  equatable: 2.1.0
  uuid: 4.5.3
  image_picker: 1.2.3
  photo_manager: 3.9.0
  auto_route: 11.1.0
  drift: 2.34.2
  sqlite3_flutter_libs: 0.5.41
  permission_handler: 12.0.3
  share_plus: 12.0.2
  file_picker: 11.0.2
  pdfx: 2.9.2
  pdf: 3.13.0
  syncfusion_flutter_pdf: 34.1.31
  flutter_dotenv: 6.0.1
  flutter_secure_storage: 10.3.1
  url_launcher: 6.3.2
  flutter_native_splash: 2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.15.1
  source_gen: 4.2.3
  auto_route_generator: 10.5.0
  analyzer: 10.2.0
  mocktail: 1.0.5
  bloc_test: 10.0.0
  test_cov: 1.0.1
  transparent_image: 2.0.1
  flutter_launcher_icons: 0.14.4
  drift_dev: 2.34.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"
  adaptive_icon_background: "#2F6BFF"
  adaptive_icon_foreground: "assets/images/splash.png"

flutter_native_splash:
  color: "#2F6BFF"
  image: assets/images/splash.png
  android: true
  ios: true